[mgr]
# Border
border_symbol = " "
border_style  = { fg = "#838ba7" }

[tabs]
active   = { fg = "#303446", bg = "#c6d0f5" }
inactive = { fg = "#c6d0f5", bg = "#51576d" }

[status]
separator_open  = ""
separator_close = ""

