[[colors.indexed_colors]]
color = "#EF9F76"
index = 16

[[colors.indexed_colors]]
color = "#F2D5CF"
index = 17

[colors.bright]
black = "#626880"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#CA9EE6"
red = "#E78284"
white = "#A5ADCE"
yellow = "#E5C890"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#51576D"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#CA9EE6"
red = "#E78284"
white = "#FFFFFF"
yellow = "#E5C890"

[colors.hints.end]
background = "#A5ADCE"
foreground = "#303446"

[colors.hints.start]
background = "#E5C890"
foreground = "#303446"

[colors.normal]
black = "#51576D"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#CA9EE6"
red = "#E78284"
white = "#FFFFFF"
yellow = "#E5C890"

[colors.primary]
background = "#282C34"
bright_foreground = "#C6D0F5"
dim_foreground = "#C6D0F5"
foreground = "#FFFFFF"

[colors.search.focused_match]
background = "#A6D189"
foreground = "#303446"

# [colors.search.footer_bar]
# background = "#A5ADCE"
# foreground = "#303446"

[colors.search.matches]
background = "#A5ADCE"
foreground = "#303446"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
